### ISSUE TITLE
Error while Launching

### ISSUE THREAD

**Issue by am3ymhatre** [sqproxy/sqredirect#4]
root@abc:/home/ubuntu# /usr/local/bin/sqredirect -i ens3 -p 11011:9100
2022-05-23 06:44:16,498 [WARNING] [pr2modules.ipdb.main] Deprecation warning https://docs.pyroute2.org/ipdb_toc.html
2022-05-23 06:44:16,502 [INFO] [main] Building eBPF program ..., cflags=['-include', 'utils.h']
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:41:9: warning: '__HAVE_BUILTIN_BSWAP32__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP32__
        ^
<command line>:4:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP32__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:42:9: warning: '__HAVE_BUILTIN_BSWAP64__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP64__
        ^
<command line>:5:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP64__ 1
        ^
In file included from <built-in>:2:
In file included from /virtual/include/bcc/bpf.h:12:
In file included from include/linux/types.h:6:
In file included from include/uapi/linux/types.h:14:
In file included from ./include/uapi/linux/posix_types.h:5:
In file included from include/linux/stddef.h:5:
In file included from include/uapi/linux/stddef.h:2:
In file included from include/linux/compiler_types.h:80:
include/linux/compiler-clang.h:43:9: warning: '__HAVE_BUILTIN_BSWAP16__' macro redefined [-Wmacro-redefined]
#define __HAVE_BUILTIN_BSWAP16__
        ^
<command line>:3:9: note: previous definition is here
#define __HAVE_BUILTIN_BSWAP16__ 1
        ^
In file included from /virtual/main.c:3:
include/linux/bpf.h:916:21: error: field has incomplete type 'enum bpf_link_type'
        enum bpf_link_type type;
                           ^
include/linux/bpf.h:916:7: note: forward declaration of 'enum bpf_link_type'
        enum bpf_link_type type;
             ^
include/linux/bpf.h:930:17: warning: declaration of 'struct bpf_link_info' will not be visible outside of this function [-Wvisibility]
                              struct bpf_link_info *info);
                                     ^
include/linux/bpf.h:1386:12: warning: declaration of 'union bpf_iter_link_info' will not be visible outside of this function [-Wvisibility]
                                        union bpf_iter_link_info *linfo,
                                              ^
include/linux/bpf.h:1392:14: warning: declaration of 'struct bpf_link_info' will not be visible outside of this function [-Wvisibility]
                                         struct bpf_link_info *info);
                                                ^
include/linux/bpf.h:1435:12: warning: declaration of 'struct bpf_link_info' will not be visible outside of this function [-Wvisibility]
                                struct bpf_link_info *info);
                                       ^
In file included from /virtual/main.c:7:
In file included from include/linux/udp.h:16:
In file included from include/net/inet_sock.h:19:
In file included from include/linux/netdevice.h:37:
In file included from include/net/net_namespace.h:36:
In file included from include/net/netns/bpf.h:9:
include/linux/bpf-netns.h:21:7: error: use of undeclared identifier 'BPF_SK_LOOKUP'
        case BPF_SK_LOOKUP:
             ^
In file included from /virtual/main.c:7:
In file included from include/linux/udp.h:16:
In file included from include/net/inet_sock.h:22:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:27:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:324:4: error: use of undeclared identifier 'KBUILD_MODNAME'
                        NL_SET_ERR_MSG_MOD(extack, "Mixing HW stats types for actions is not supported");
                        ^
include/linux/netlink.h:102:27: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                 ^
In file included from /virtual/main.c:7:
In file included from include/linux/udp.h:16:
In file included from include/net/inet_sock.h:22:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:27:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:324:4: error: expected ';' at end of declaration
include/linux/netlink.h:102:42: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                                ^
In file included from /virtual/main.c:7:
In file included from include/linux/udp.h:16:
In file included from include/net/inet_sock.h:22:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:27:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:359:3: error: use of undeclared identifier 'KBUILD_MODNAME'
                NL_SET_ERR_MSG_MOD(extack, "Driver supports only default HW stats type \"any\"");
                ^
include/linux/netlink.h:102:27: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                 ^
In file included from /virtual/main.c:7:
In file included from include/linux/udp.h:16:
In file included from include/net/inet_sock.h:22:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:27:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:359:3: error: expected ';' at end of declaration
include/linux/netlink.h:102:42: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                                ^
In file included from /virtual/main.c:7:
In file included from include/linux/udp.h:16:
In file included from include/net/inet_sock.h:22:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:27:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:363:3: error: use of undeclared identifier 'KBUILD_MODNAME'
                NL_SET_ERR_MSG_MOD(extack, "Driver does not support selected HW stats type");
                ^
include/linux/netlink.h:102:27: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                 ^
In file included from /virtual/main.c:7:
In file included from include/linux/udp.h:16:
In file included from include/net/inet_sock.h:22:
In file included from include/net/sock.h:59:
In file included from include/linux/filter.h:27:
In file included from include/net/sch_generic.h:21:
include/net/flow_offload.h:363:3: error: expected ';' at end of declaration
include/linux/netlink.h:102:42: note: expanded from macro 'NL_SET_ERR_MSG_MOD'
        NL_SET_ERR_MSG((extack), KBUILD_MODNAME ": " msg)
                                                ^
7 warnings and 8 errors generated.
Traceback (most recent call last):
  File "/usr/local/bin/sqredirect", line 8, in <module>
    sys.exit(sqredirect())
  File "/usr/local/lib/python3.8/dist-packages/sqredirect/redirect.py", line 342, in sqredirect
    main(args.ports, args.interface)
  File "/usr/local/lib/python3.8/dist-packages/sqredirect/redirect.py", line 152, in main
    bpf = BPF(src_file="redirect.c", cflags=cflags, debug=0)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 347, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module b'redirect.c'

**Comment by spumer** [comment]
Please provide some info:

Kernel version: uname -r
BCC Tools version: python3 -c 'import bcc; print(bcc.__version__)'

---
And please check your bcc version is new, like in this comment: https://github.com/sqproxy/sqproxy/issues/115#issuecomment-1090722691

**Comment by am3ymhatre** [comment]
> Please provide some info:
> 
> Kernel version: `uname -r` BCC Tools version: `python3 -c 'import bcc; print(bcc.__version__)'`
> 
> And please check your bcc version is new, like in this comment: [sqproxy/sqproxy#115 (comment)](https://github.com/sqproxy/sqproxy/issues/115#issuecomment-1090722691)

Kernel Version : 5.15 (even tried on 5.18)
python3 -c 'import bcc; print(bcc.__version__)' = 0.12.0

**Comment by spumer** [comment]
Do you have `linux-headers-$(uname -r)` package installed?

**Comment by spumer** [comment]
Stalled
